name: Working Group Updates
description: Idea or request for some update to a Working Group Section
labels: [':thought_balloon: idea']
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for contributing to our project!** :green_heart:

  - type: textarea
    id: which
    attributes:
      label: Which
      description: Which Working Group needs or wants this update?
      placeholder: |
        Give context and describe the problem, challenge or opportunity you see
    validations:
      required: true

  - type: textarea
    id: what
    attributes:
      label: What
      description: What would you like to see updated?
      placeholder: |
        For example describe a change in members, a change in lead member,
        a new meeting minute update, ...
    validations:
      required: true

 
